-- MySQL Script generated by MySQL Workbench
-- Wed Dec  5 17:42:00 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema resortdo_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema resortdo_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `resortdo_db` DEFAULT CHARACTER SET utf8 ;
USE `resortdo_db` ;

-- -----------------------------------------------------
-- Table `resortdo_db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resortdo_db`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hashID` VARCHAR(100) NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `token` TEXT NULL,
  `sts` VARCHAR(1) NULL DEFAULT 'A',
  `created` DATETIME NOT NULL,
  `updated` DATETIME NULL,
  `deleted` VARCHAR(1) NULL DEFAULT 'N',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT;


-- -----------------------------------------------------
-- Table `resortdo_db`.`banners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resortdo_db`.`banners` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hashID` VARCHAR(100) NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `primeiraLinha` VARCHAR(45) NOT NULL,
  `segundaLinha` VARCHAR(45) NOT NULL,
  `inicio` VARCHAR(45) NULL,
  `fim` VARCHAR(45) NULL,
  `sts` VARCHAR(1) NULL DEFAULT 'A',
  `ordem` VARCHAR(10) NOT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `deleted` VARCHAR(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT;


-- -----------------------------------------------------
-- Table `resortdo_db`.`depoimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resortdo_db`.`depoimentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hashID` VARCHAR(100) NOT NULL,
  `depoimento` TEXT NOT NULL,
  `nomePessoa` VARCHAR(45) NOT NULL,
  `sts` VARCHAR(1) NULL DEFAULT 'A',
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `deleted` VARCHAR(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT;


-- -----------------------------------------------------
-- Table `resortdo_db`.`videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resortdo_db`.`videos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hashID` VARCHAR(45) NOT NULL,
  `titulo` VARCHAR(300) NOT NULL,
  `descricao` TEXT NOT NULL,
  `idvideo` VARCHAR(100) NOT NULL,
  `sts` VARCHAR(1) NOT NULL DEFAULT 'A',
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `deleted` VARCHAR(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resortdo_db`.`midias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resortdo_db`.`midias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hashID` VARCHAR(45) NOT NULL,
  `titulo` VARCHAR(500) NOT NULL,
  `url` VARCHAR(500) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `sts` VARCHAR(1) NOT NULL DEFAULT 'A',
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `deleted` VARCHAR(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resortdo_db`.`contatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resortdo_db`.`contatos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hashID` VARCHAR(45) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `contato` VARCHAR(500) NOT NULL,
  `endereco` VARCHAR(500) NOT NULL,
  `sts` VARCHAR(1) NOT NULL DEFAULT 'A',
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `deleted` VARCHAR(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resortdo_db`.`imagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resortdo_db`.`imagens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hashID` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(145) NOT NULL,
  `idItem` VARCHAR(200) NOT NULL,
  `ref` VARCHAR(200) NOT NULL,
  `sts` VARCHAR(45) NOT NULL DEFAULT 'A',
  `pathRelative` VARCHAR(300) NULL,
  `pathLarge` VARCHAR(300) NULL,
  `pathMedium` VARCHAR(300) NULL,
  `pathThumb` VARCHAR(300) NULL,
  `created` VARCHAR(45) NULL,
  `updated` VARCHAR(45) NULL,
  `deleted` VARCHAR(45) NULL DEFAULT 'N',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resortdo_db`.`atracoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resortdo_db`.`atracoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hashID` VARCHAR(100) NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `sts` VARCHAR(1) NULL DEFAULT 'A',
  `ordem` VARCHAR(10) NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `deleted` VARCHAR(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT;


-- -----------------------------------------------------
-- Table `resortdo_db`.`caldas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resortdo_db`.`caldas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hashID` VARCHAR(100) NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `subtitulo` VARCHAR(200) NOT NULL,
  `descricao` TEXT NOT NULL,
  `sts` VARCHAR(1) NULL DEFAULT 'A',
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `deleted` VARCHAR(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT;


-- -----------------------------------------------------
-- Table `resortdo_db`.`resort`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resortdo_db`.`resort` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hashID` VARCHAR(100) NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `subtitulo` VARCHAR(200) NOT NULL,
  `titulo_parque` VARCHAR(45) NULL,
  `descricao_parque` TEXT NULL,
  `titulo_acomodacoes` VARCHAR(45) NULL,
  `descricao_acomodacoes` TEXT NULL,
  `titulo_gastronomia` VARCHAR(45) NULL,
  `descricao_gastronomia` TEXT NULL,
  `titulo_lago` VARCHAR(45) NULL,
  `descricao_lago` TEXT NULL,
  `titulo_galeria` VARCHAR(45) NULL,
  `sts` VARCHAR(1) NOT NULL DEFAULT 'A',
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `deleted` VARCHAR(1) NULL DEFAULT 'N',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT;


-- -----------------------------------------------------
-- Table `resortdo_db`.`diversao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resortdo_db`.`diversao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hashID` VARCHAR(100) NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `subtitulo` VARCHAR(200) NOT NULL,
  `titulo_half` VARCHAR(45) NULL,
  `descricao_half` TEXT NULL,
  `titulo_lancha` VARCHAR(45) NULL,
  `descricao_lancha` TEXT NULL,
  `titulo_parque` VARCHAR(45) NULL,
  `descricao_parque` TEXT NULL,
  `titulo_simulador` VARCHAR(45) NULL,
  `descricao_simulador` TEXT NULL,
  `titulo_caiaque` VARCHAR(45) NULL,
  `descricao_caiaque` TEXT NULL,
  `titulo_standup` VARCHAR(45) NULL,
  `descricao_standup` TEXT NULL,
  `titulo_galeria` VARCHAR(45) NULL,
  `sts` VARCHAR(1) NOT NULL DEFAULT 'A',
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `deleted` VARCHAR(1) NULL DEFAULT 'N',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT;


-- -----------------------------------------------------
-- Table `resortdo_db`.`tranquilidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resortdo_db`.`tranquilidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hashID` VARCHAR(100) NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `subtitulo` VARCHAR(200) NOT NULL,
  `titulo_piscina` VARCHAR(45) NULL,
  `descricao_piscina` TEXT NULL,
  `titulo_prainha` VARCHAR(45) NULL,
  `descricao_prainha` TEXT NULL,
  `titulo_sauna` VARCHAR(45) NULL,
  `descricao_sauna` TEXT NULL,
  `titulo_gastronomia` VARCHAR(45) NULL,
  `descricao_gastronomia` TEXT NULL,
  `titulo_acomodacoes` VARCHAR(45) NULL,
  `descricao_acomodacoes` TEXT NULL,
  `titulo_galeria` VARCHAR(45) NULL,
  `sts` VARCHAR(1) NOT NULL DEFAULT 'A',
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `deleted` VARCHAR(1) NULL DEFAULT 'N',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
